#端口
server:
  port: 8083

mybatis-plus:
  type-aliases-package: com.mygod.login.po
  mapper-locations: classpath:/mapper/*Mapper.xml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:4000/mygod
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


#引入jdbc配置(application-jdbc)(文件要在同级目录下)
#spring:
#  profiles:
#    include: jdbc